"""LidMagnit

Revision ID: 3415570f543b
Revises: a1912b719776
Create Date: 2025-03-26 22:56:12.759012

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3415570f543b"
down_revision: str | None = "a1912b719776"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_lidmagnit",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("is_clicked_channel", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_clicked_article", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "create_datetime", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users_lidmagnit")),
        sa.UniqueConstraint("user_id", name=op.f("uq_users_lidmagnit_user_id")),
    )
    op.create_unique_constraint(op.f("uq_users_channel_user_id"), "users_channel", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_channel_user_id"), "users_channel", type_="unique")
    op.drop_table("users_lidmagnit")
    # ### end Alembic commands ###
