"""clicked

Revision ID: 8281a859d6c9
Revises: d0cffdce74e0
Create Date: 2025-03-18 00:23:16.463185

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8281a859d6c9"
down_revision: str | None = "d0cffdce74e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_clicked_channel", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.add_column(
        "users", sa.Column("is_clicked_article", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.create_unique_constraint(op.f("uq_users_user_id"), "users", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_user_id"), "users", type_="unique")
    op.drop_column("users", "is_clicked_article")
    op.drop_column("users", "is_clicked_channel")
    # ### end Alembic commands ###
