name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run command on remote server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 59999
          script_stop: true
          script: |
            cd /root/ankibenefitbot;
            git fetch --all;
            git reset --hard origin/main;
            docker compose -f docker-compose.yml down --rmi all
            docker compose -f docker-compose.yml up -d

  deploy:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
